'use strict';
const CODES = Object.freeze({
  UNKNOWN_TOOL: 'UNKNOWN_TOOL',
  INVALID_INPUT: 'INVALID_INPUT',
  FORBIDDEN: 'FORBIDDEN',
  SCOPE: 'SCOPE',
  NOT_PENDING: 'NOT_PENDING',
  EXPIRED: 'EXPIRED',
  UPSTREAM: 'UPSTREAM',
  UPSTREAM_NOT_FOUND: 'UPSTREAM_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  SENSITIVE_FILE: 'SENSITIVE_FILE',
  SECRET_IN_CONTENT: 'SECRET_IN_CONTENT',
  GITHUB_AUTH: 'GITHUB_AUTH',
  GITHUB_APP_REQUIRED: 'GITHUB_APP_REQUIRED',
  CREDENTIAL_MISSING: 'CREDENTIAL_MISSING',
  PROVIDER_AUTH: 'PROVIDER_AUTH',
  STAGING_REQUIRED: 'STAGING_REQUIRED',
});
const HTTP_STATUS = { UNKNOWN_TOOL: 404, INVALID_INPUT: 400, FORBIDDEN: 403, SCOPE: 403, NOT_PENDING: 409, EXPIRED: 409, UPSTREAM: 502, UPSTREAM_NOT_FOUND: 404,
  CONFLICT: 409, SENSITIVE_FILE: 400, SECRET_IN_CONTENT: 400, GITHUB_AUTH: 502, GITHUB_APP_REQUIRED: 503,
  CREDENTIAL_MISSING: 503, PROVIDER_AUTH: 502, STAGING_REQUIRED: 409 };

class GatewayError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'GatewayError';
    this.code = code;
    this.details = details;
  }
}

module.exports = { GatewayError, CODES, HTTP_STATUS };
