'use strict';
// Fila fixa do Cortex: as tarefas são Issues do GitHub com o rótulo "cortex-fila" (grátis, sem Firestore).
// A cada 15 minutos o workflow "Fila do Cortex" roda este script: conclui o que terminou, reenfileira o que
// falhou (com espera crescente), alerta quando uma tarefa trava e despacha as próximas em até 3 pistas.
const REPO = process.env.REPO || 'gilcambe/nexia';
const BASE_URL = process.env.NEXIA_URL || 'https://nexia.gcbezerra.workers.dev';
const PISTAS = 3;
const MAX_TENTATIVAS = 12;
const CONFIAVEIS = ['OWNER', 'MEMBER', 'COLLABORATOR'];
const L = { fila: 'cortex-fila', rodando: 'cortex-rodando', feito: 'cortex-feito', travado: 'cortex-travado' };

const nomes = i => (i.labels || []).map(l => (typeof l === 'string' ? l : l.name));
const numeroDe = (labels, prefixo) => {
  const m = labels.map(n => new RegExp(`^${prefixo}-(\\d+)$`).exec(n)).find(Boolean);
  return m ? Number(m[1]) : 0;
};
const minutos = (agora, iso) => (agora - new Date(iso).getTime()) / 60000;

// Função pura: recebe issues e execuções e devolve a lista de ações. Fácil de testar.
function decidir({ issues, runs, agora = Date.now(), pistas = PISTAS }) {
  const acoes = [];
  const ultimaRun = n => runs.filter(r => r.name === `Cortex #${n}`).sort((a, b) => b.id - a.id)[0] || null;
  const validas = issues.filter(i => !i.pull_request && CONFIAVEIS.includes(i.author_association) && nomes(i).includes(L.fila));
  const pistasEmUso = new Set();
  let ativas = 0;

  for (const i of validas) {
    const ls = nomes(i);
    if (ls.includes(L.feito) || ls.includes(L.travado)) continue;
    if (!ls.includes(L.rodando)) continue;
    const run = ultimaRun(i.number);
    const pista = numeroDe(ls, 'pista');
    if (run && run.status === 'completed') {
      if (run.conclusion === 'success') { acoes.push({ tipo: 'concluir', numero: i.number, run: run.id }); continue; }
      const t = numeroDe(ls, 'tentativa') + 1;
      acoes.push(t >= MAX_TENTATIVAS
        ? { tipo: 'travar', numero: i.number, tentativas: t, run: run.id }
        : { tipo: 'reenfileirar', numero: i.number, tentativa: t, run: run.id, conclusao: run.conclusion });
      continue;
    }
    if (!run && minutos(agora, i.updated_at) > 20) { acoes.push({ tipo: 'reenfileirar', numero: i.number, tentativa: numeroDe(ls, 'tentativa'), run: null, conclusao: 'sem execução' }); continue; }
    ativas++;
    if (pista) pistasEmUso.add(pista);
  }

  const fila = validas
    .filter(i => { const ls = nomes(i); return !ls.includes(L.rodando) && !ls.includes(L.feito) && !ls.includes(L.travado); })
    .sort((a, b) => a.number - b.number);
  for (const i of fila) {
    if (ativas >= pistas) break;
    const t = numeroDe(nomes(i), 'tentativa');
    const run = ultimaRun(i.number);
    const espera = Math.min(120, 15 * t);
    if (run && run.status === 'completed' && minutos(agora, run.updated_at || run.created_at) < espera) continue; // espera crescente entre tentativas
    let pista = 1; while (pistasEmUso.has(pista)) pista++;
    pistasEmUso.add(pista); ativas++;
    acoes.push({ tipo: 'despachar', numero: i.number, pista, tarefa: String(i.body || '').trim() });
  }
  // Reenfileirados neste ciclo voltam à fila no próximo (o rótulo "rodando" sai agora).
  return acoes;
}

async function gh(token, method, path, body) {
  const r = await fetch(`https://api.github.com/repos/${REPO}${path}`, {
    method, headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const txt = await r.text();
  let json = null; try { json = JSON.parse(txt); } catch { /* vazio */ }
  return { status: r.status, json };
}

async function executar(token, acao) {
  const n = acao.numero;
  const addLabel = l => gh(token, 'POST', `/issues/${n}/labels`, { labels: [l] });
  const delLabel = l => gh(token, 'DELETE', `/issues/${n}/labels/${encodeURIComponent(l)}`);
  const comentar = t => gh(token, 'POST', `/issues/${n}/comments`, { body: `${t}\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_` });
  if (acao.tipo === 'despachar') {
    await addLabel(L.rodando); await addLabel(`pista-${acao.pista}`);
    const d = await gh(token, 'POST', '/actions/workflows/smoke-logado.yml/dispatches', {
      ref: 'develop', inputs: { url: BASE_URL, task: acao.tarefa, autonomia: '3', pista: String(acao.pista), modo: 'economico', tarefa_id: String(n) },
    });
    if (d.status !== 204) { await delLabel(L.rodando); await comentar(`Não consegui disparar o Cortex (${d.status}). Tento de novo no próximo ciclo.`); }
  } else if (acao.tipo === 'concluir') {
    await delLabel(L.rodando); await addLabel(L.feito);
    await comentar(`Concluída pelo Cortex: https://github.com/${REPO}/actions/runs/${acao.run}`);
    await gh(token, 'PATCH', `/issues/${n}`, { state: 'closed', state_reason: 'completed' });
  } else if (acao.tipo === 'reenfileirar') {
    await delLabel(L.rodando);
    for (const l of [`tentativa-${acao.tentativa - 1}`]) if (acao.tentativa > 1) await delLabel(l);
    await addLabel(`tentativa-${acao.tentativa}`);
  } else if (acao.tipo === 'travar') {
    await delLabel(L.rodando); await addLabel(L.travado);
    await comentar(`Tarefa travada depois de ${acao.tentativas} tentativas (última: https://github.com/${REPO}/actions/runs/${acao.run}). Precisa de olhar humano.`);
  }
}

async function main() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('Falta GITHUB_TOKEN.');
  for (const l of Object.values(L)) await gh(token, 'POST', '/labels', { name: l, color: '1d76db' });
  const issues = (await gh(token, 'GET', `/issues?state=open&labels=${L.fila}&per_page=50`)).json || [];
  const runs = ((await gh(token, 'GET', '/actions/workflows/smoke-logado.yml/runs?per_page=60')).json || {}).workflow_runs || [];
  const acoes = decidir({ issues, runs });
  for (const a of acoes) { console.log(`${a.tipo} #${a.numero}${a.pista ? ` pista ${a.pista}` : ''}${a.tentativa ? ` tentativa ${a.tentativa}` : ''}`); await executar(token, a); }
  console.log(`${issues.length} na fila, ${acoes.length} ação(ões).`);
}

module.exports = { decidir, MAX_TENTATIVAS };
if (require.main === module) main().catch(e => { console.error(e.message); process.exit(1); });
